### ISSUE TITLE
googlechart.watermark_image is required

### ISSUE THREAD

**Issue by djowett** [eea/eea.googlecharts#5]
which means I can't change *any* setting without setting a watermark image first

**Comment by zotya** [comment]
Hi, the watermark is mandatory.
You can do a workaround, set a dummy image, and set it's size to 0x0

**Comment by alecghica** [comment]
@djowett this is how the system was built, having the watermak mandatory. If you think it should not either submit a new issue or a pulll request with the changes you think appropriate.
